// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJo1yLM5V7LeYNtaz1xU8j99aDUcDioI',
    appId: '1:934494699322:web:5787571d3d9afda78a9a03',
    messagingSenderId: '934494699322',
    projectId: 'crud-tarea8-95b55',
    authDomain: 'crud-tarea8-95b55.firebaseapp.com',
    storageBucket: 'crud-tarea8-95b55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXfDIE-Lo4QP2ymQazNHEbs2inK_96dI4',
    appId: '1:934494699322:android:215294ba48fbd95d8a9a03',
    messagingSenderId: '934494699322',
    projectId: 'crud-tarea8-95b55',
    storageBucket: 'crud-tarea8-95b55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5pww8kJ_yCVmX5pa0NugU1usQRtfqv-M',
    appId: '1:934494699322:ios:0937fdfd2476ef1b8a9a03',
    messagingSenderId: '934494699322',
    projectId: 'crud-tarea8-95b55',
    storageBucket: 'crud-tarea8-95b55.appspot.com',
    iosBundleId: 'com.example.tarea8Crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5pww8kJ_yCVmX5pa0NugU1usQRtfqv-M',
    appId: '1:934494699322:ios:0937fdfd2476ef1b8a9a03',
    messagingSenderId: '934494699322',
    projectId: 'crud-tarea8-95b55',
    storageBucket: 'crud-tarea8-95b55.appspot.com',
    iosBundleId: 'com.example.tarea8Crudfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoJo1yLM5V7LeYNtaz1xU8j99aDUcDioI',
    appId: '1:934494699322:web:22c440e49992b8ad8a9a03',
    messagingSenderId: '934494699322',
    projectId: 'crud-tarea8-95b55',
    authDomain: 'crud-tarea8-95b55.firebaseapp.com',
    storageBucket: 'crud-tarea8-95b55.appspot.com',
  );
}
